/**
 * MangoVault Server-Side Verification Utility
 * Handles secure cryptographic validation of Pi Network transactions.
 */

import axios from 'axios';

const PI_API_KEY = "your_pi_network_api_key_here"; // Secured in environment variables in production

export const MangoVault = {
  /**
   * Verifies a Pi Network payment ID against the Pi API.
   * @param {string} paymentId - The ID generated by the Pi SDK.
   * @param {number} expectedAmount - The amount (e.g., 10.0 for Node Activation).
   * @returns {Promise<Object>} - Verification status and transaction details.
   */
  async verifyPiPayment(paymentId, expectedAmount = 10.0) {
    try {
      console.log(`[MangoVault] Initiating server-side verification for Payment: ${paymentId}`);

      const response = await axios.get(`https://api.minepi.com/v2/payments/${paymentId}`, {
        headers: {
          'Authorization': `Key ${PI_API_KEY}`
        }
      });

      const payment = response.data;

      // Condition Check: Must be completed and match the expected amount
      if (payment.status.completed && parseFloat(payment.amount) === expectedAmount) {
        console.log(`[MangoVault] Success: Payment validated. TXID: ${payment.transaction.txid}`);
        return { success: true, txid: payment.transaction.txid, metadata: payment.metadata };
      }

      throw new Error("Payment status incomplete or amount mismatch.");
    } catch (error) {
      console.error("[MangoVault] Verification Failed:", error.response?.data || error.message);
      return { success: false, error: error.message };
    }
  }
};