const PDFDocument = require('pdfkit');
const nodemailer = require('nodemailer');
const fs = require('fs');
const path = require('path');

/**
 * Mango Receipt Service
 * Converts Amadeus Booking Data to PDF and sends via Email
 */
const receiptService = {
    sendDigitalVoucher: async (bookingData, mngPoints = "0.00") => {
        const { email, hotelName, price, reservationNumber, piAmount, checkInDate } = bookingData;
        const voucherDir = path.join(__dirname, '../vouchers');
        
        if (!fs.existsSync(voucherDir)) fs.mkdirSync(voucherDir);
        const filePath = path.join(voucherDir, `Voucher_${reservationNumber}.pdf`);

        // 1. Generate PDF
        const doc = new PDFDocument({ margin: 50 });
        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Mango Branding in PDF
        doc.fillColor('#f59e0b').fontSize(26).text('MANGO TRAVEL', { align: 'right' });
        doc.fontSize(10).fillColor('#888').text('GLOBAL LOGISTICS & STAY', { align: 'right' });
        doc.moveDown(2);

        doc.fillColor('#000').fontSize(18).text('BOOKING CONFIRMATION', { underline: true });
        doc.moveDown();
        doc.fontSize(12).text(`Reservation ID: ${reservationNumber}`);
        doc.text(`Property: ${hotelName}`);
        doc.text(`Check-in Date: ${checkInDate}`);
        doc.moveDown();

        doc.rect(50, doc.y, 500, 40).fill('#fff9e6').stroke('#f59e0b');
        doc.fillColor('#d97706').text(`Total Paid: ${piAmount} π (MNG Points: ${mngPoints})`, 60, doc.y + 15, { font: 'Helvetica-Bold' });
        
        doc.moveDown(10);
        doc.fillColor('#999').fontSize(8).text('This is an automated voucher generated by Mango OS. Valid for check-in via Pi Browser Auth.', { align: 'center' });

        doc.end();

        // 2. Setup Email Transporter (Configure with your SMTP)
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: 587,
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS
            }
        });

        // 3. Send Mail
        const mailOptions = {
            from: '"Mango Concierge" <noreply@mango.ceo>',
            to: email,
            subject: `[Mango Travel] Confirmed: ${hotelName} Reservation`,
            html: `
                <div style="font-family: 'Inter', Arial, sans-serif; background-color: #050505; color: white; padding: 40px; border-radius: 30px; border: 1px solid #f59e0b; max-width: 600px; margin: auto;">
                    <div style="text-align: right; margin-bottom: 30px;">
                        <h1 style="color: #f59e0b; margin: 0; font-size: 26px; font-style: italic;">MANGO TRAVEL</h1>
                        <p style="color: #666; font-size: 10px; margin: 0; letter-spacing: 2px;">GLOBAL LOGISTICS & STAY</p>
                    </div>
                    <h2 style="font-size: 22px; border-bottom: 2px solid #333; padding-bottom: 15px; text-transform: uppercase;">Booking Secured</h2>
                    <p style="font-size: 15px; line-height: 1.6;">Your upcoming stay at <strong>${hotelName}</strong> has been successfully processed through the Pi Network ecosystem.</p>
                    <p style="font-size: 15px;">Reservation ID: <span style="color: #f59e0b; font-family: monospace; font-weight: bold;">${reservationNumber}</span></p>
                    
                    <div style="margin: 35px 0; padding: 25px; background: rgba(245, 158, 11, 0.08); border: 1px dashed rgba(245, 158, 11, 0.4); border-radius: 20px; text-align: center;">
                        <p style="margin: 0; font-size: 11px; color: #f59e0b; text-transform: uppercase; font-weight: 800; letter-spacing: 1px;">Real-time Asset Sync</p>
                        <p style="margin: 10px 0 0 0; font-size: 24px; font-weight: 900; color: #ffffff;">Current Balance: ${mngPoints} <span style="color: #f59e0b;">MNG</span></p>
                        <p style="margin: 5px 0 0 0; font-size: 10px; color: #555;">(Rewards synchronized via Mango OS Hub)</p>
                    </div>
                    
                    <p style="font-size: 11px; color: #444; text-align: center; margin-top: 30px;">This is a digital confirmation. Please refer to the attached PDF for full check-in details.</p>
                </div>
            `,
            attachments: [{ filename: `Voucher_${reservationNumber}.pdf`, path: filePath }]
        };

        try {
            await transporter.sendMail(mailOptions);
            return { success: true, filePath };
        } catch (error) {
            console.error('Email dispatch failed:', error);
            throw error;
        }
    },

    /**
     * Weekly Ranking Winner Notification
     * Sends a mobile-optimized congratulatory message via Nodemailer
     */
    sendBonusCongratulation: async (email, username, bonusAmount, activitySummary = []) => {
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: 587,
            auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS }
        });

        const mailOptions = {
            from: '"Mango Universe" <awards@mango.ceo>',
            to: email,
            subject: `🏆 Congratulations! You are this week's #1 Mango Pioneer!`,
            html: `
                <div style="background-color: #050505; color: white; padding: 30px; border-radius: 30px; font-family: 'Inter', sans-serif; text-align: center; border: 2px solid #f59e0b; max-width: 500px; margin: auto;">
                    <h1 style="color: #f59e0b; font-style: italic;">VICTORY!</h1>
                    <p style="font-size: 18px;">Hello, <strong>${username}</strong>!</p>
                    <p style="font-size: 16px; line-height: 1.5;">You've conquered the weekly rankings through your incredible activity.</p>
                    <div style="background: rgba(245, 158, 11, 0.1); padding: 20px; border-radius: 15px; margin: 20px 0;">
                        <p style="margin: 0; color: #f59e0b; font-weight: 800; font-size: 12px; text-transform: uppercase;">Weekly Bonus Awarded</p>
                        <h2 style="margin: 10px 0; font-size: 32px;">${bonusAmount} MNG</h2>
                    </div>
                    
                    ${activitySummary.length > 0 ? `
                    <div style="text-align: left; background: rgba(255,255,255,0.05); padding: 20px; border-radius: 20px; margin-bottom: 20px;">
                        <p style="color: #f59e0b; font-weight: 900; font-size: 11px; text-transform: uppercase; margin-bottom: 10px;">This Week's Highlights</p>
                        <ul style="list-style: none; padding: 0; margin: 0;">
                            ${activitySummary.map(act => `
                                <li style="font-size: 13px; margin-bottom: 8px; color: #ccc;">📍 <b>${act.title}</b> <span style="font-size: 10px; color: #666;">(${new Date(act.date).toLocaleDateString()})</span></li>
                            `).join('')}
                        </ul>
                    </div>
                    ` : ''}

                    <p style="font-size: 12px; color: #666; margin-bottom: 20px;">Check your profile for the updated balance. Keep leading the way!</p>
                    <p style="margin-top: 20px; font-weight: bold; color: #f59e0b;">- Chairman SkyMango -</p>
                </div>
            `
        };

        try {
            await transporter.sendMail(mailOptions);
            return { success: true, filePath };
        } catch (error) {
            console.error('Email dispatch failed:', error);
            throw error;
        }
    }
};

module.exports = receiptService;